# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "dclucas"
description: > # this means to ignore newlines until "email:"
   A nerdy text bag

email: diogo.lucas@gmail.com
#blog logo
logo: "/assets/images/noun_12327.png"
# blog cover
cover: "/assets/images/15452746694_3c035e2618_o.jpg"

excerpt_separator: <!--more-->

name: 'Diogo Lucas'
author: 'Diogo Lucas'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://dclucas.github.io/" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/diogoclucas
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dclucas
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
